apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-ms
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - user-service.yaml
  - order-service.yaml
  - audit-log-service.yaml
  - web-portal.yaml
  - ingress.yaml
